var App = Ember.Application.create();

// Router
// Smilar to rails routes
App.Router.map(function() {
  // /#/tables'
  this.resource('tables', function () {
    // /#/tables/:table_id (current path is combined with parent path)
    this.resource('table', { path: ':table_id'}); // Must have name of resource before id (not just id like in rails)
  });
});

// Routes
// Run code when urls are visited and load data and assign to a controller
App.TablesRoute = Ember.Route.extend({ // Extend like inheritance
  model: function() {
    return App.Table.find(); // Without parameters to return all tables
  }
});

// Auto generated by ember
App.TableRoute = Ember.Route.extend({
  model: function(params) {
    return App.Table.find(params.table_id);
  }
});

// Controllers
// Deliver model data to views and templates. Have a model property
App.TablesController = Ember.ArrayController.extend(); // Must match the route name

App.TableController = Ember.ObjectController.extend(); // Autogenerated by ember

// Models
// Store specify how we access data
App.Store = DS.Store.extend({
  revision: 11, // Ember.Data has versions, this specifies the latest
  adapter: 'DS.FixtureAdapter' // Loads data locally. Good to initial setup
});

// Setup the tables model
App.Table = DS.Model.extend();

App.Table.FIXTURES = [
  { id: 1 },
  { id: 2 },
  { id: 3 },
  { id: 4 },
  { id: 5 },
  { id: 6 }
];